spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:nana_xinh}
    username: ${DB_USERNAME:nana}
    password: ${DB_PASSWORD:change_me}
  jpa:
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
